"""
TradeNexus Enterprise Pilot Agreement & SLA Generator (ANTIGRAVITY Ω∞)
Generates statutory 30-Day Paid Pilot Term Sheets, Service Level Agreements (SLAs),
and Demurrage Indemnity Guarantees for Indian export enterprises.
"""

import os
import hashlib
from datetime import datetime, timezone, timedelta
from typing import Dict, Any, Optional

class PilotAgreementGenerator:
    DEFAULT_MONTHLY_FEE_INR = 35000.0
    DEFAULT_DEMURRAGE_INDEMNITY_CAP_INR = 500000.0
    DEFAULT_CONSIGNMENTS_QUOTA = 50

    @classmethod
    def generate_pilot_agreement(
        cls,
        company_name: str,
        authorized_signatory: str,
        signatory_title: str,
        registered_address: str,
        iec_code: str,
        gstin: str,
        monthly_fee_inr: float = DEFAULT_MONTHLY_FEE_INR,
        consignments_quota: int = DEFAULT_CONSIGNMENTS_QUOTA,
        effective_date_str: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generates a legally structured 30-day enterprise pilot agreement docket.
        """
        now = datetime.now(timezone.utc)
        effective_date = effective_date_str or now.strftime("%B %d, %Y")
        expiry_date = (now + timedelta(days=30)).strftime("%B %d, %Y")
        contract_id = f"TN-PILOT-{now.strftime('%Y%m%d')}-{hashlib.sha256(company_name.encode()).hexdigest()[:8].upper()}"

        md_contract = f"""# ENTERPRISE PILOT SERVICE AGREEMENT & SLA
**Contract Reference**: `{contract_id}`  
**Effective Date**: {effective_date} | **Pilot Term**: 30 Calendar Days (Expiring: {expiry_date})

---

### PARTIES
1. **TRADENEXUS AI TECHNOLOGIES** ("Service Provider")  
   Registered Office: Peenya & Koramangala Technology Hub, Bengaluru, Karnataka, India  
   Represented by: Aditya Mehra, Founder & Managing Director

2. **{company_name.upper()}** ("Customer")  
   Corporate Address: {registered_address}  
   DGFT IEC: `{iec_code}` | GSTIN: `{gstin}`  
   Authorized Signatory: **{authorized_signatory}**, {signatory_title}

---

### 1. SCOPE OF PILOT SERVICES
Service Provider grants Customer an enterprise evaluation license to the TradeNexus AI Autonomous Customs Clearance Engine during the 30-day pilot term:
1. **Automated Pre-Shipment Clearance**: Instant (< 60 seconds) verification of commercial export invoices, packing lists, and ICEGATE shipping bills prior to port gate-in.
2. **Harmonized System (HS) Code Intelligence**: Deterministic tariff reconciliation against WCO 2026 revisions and DGFT ITC-HS statutory schedules.
3. **EU CBAM Compliance Automation**: Automated generation of European Union Carbon Border Adjustment Mechanism (CBAM) embedded emissions XML declarations conforming to Regulation (EU) 2023/956.
4. **Export Control & SCOMET Auditing**: Identification of dual-use defense and chemical restrictions under DGFT SCOMET Category 6.
5. **Consignment Allowance**: Up to **{consignments_quota} export consignments** audited during the 30-day term.

---

### 2. COMMERCIAL TERMS & CONVERSION OPTION
- **Pilot Evaluation Fee**: **₹{monthly_fee_inr:,.2f} + 18% GST** (Non-refundable, payable upon agreement execution).
- **Annual Enterprise Conversion**: Customer may convert this pilot into an Annual Enterprise Subscription at the preferential rate of **₹{(monthly_fee_inr * 10):,.2f}/year** (reflecting 2 months complimentary software fee), crediting 100% of the Pilot Evaluation Fee toward the first annual contract year.

---

### 3. SERVICE LEVEL AGREEMENT (SLA) & PERFORMANCE GUARANTEE
- **Clearance Latency SLA**: TradeNexus guarantees that 99.0% of document dockets submitted via API, web portal, or email upload will be audited with verified results within **60 seconds**.
- **System Uptime**: 99.9% platform availability across Indian Customs (ICEGATE) operational windows.

---

### 4. DEMURRAGE INDEMNITY GUARANTEE & LIABILITY CAP
1. **Demurrage Shield**: In the event that any export consignment audited and marked **"APPROVED"** by TradeNexus suffers a customs hold, inspection quarantine, or port demurrage penalty resulting *solely and directly* from an erroneous HS-code classification or CBAM calculation generated by TradeNexus:
   - Service Provider will credit 100% of the incurred direct port demurrage fees against Customer's account, capped at a maximum of **₹{cls.DEFAULT_DEMURRAGE_INDEMNITY_CAP_INR:,.2f}** per occurrence.
2. **Exclusions**: Indemnity does not apply to cargo inspection delays caused by physical cargo discrepancies, contraband, undeclared hazardous goods, or government-wide port strikes.

---

### 5. CONFIDENTIALITY & DATA SECURITY
- All Customer export invoices, consignee identities, pricing matrices, and bills of materials remain the strict, proprietary intellectual property of the Customer.
- All transactional data is encrypted at rest using AES-256 and in transit via TLS 1.3.

---

### EXECUTION & ACCEPTANCE

**For TradeNexus AI Technologies:**  
Aditya Mehra, Founder & Managing Director  
Signature: `[DIGITALLY SIGNED - ADITYA MEHRA]`  
Date: {effective_date}

**For {company_name}:**  
{authorized_signatory}, {signatory_title}  
Signature: __________________________________  
Date: _______________________________________  
"""

        # Generate HTML version for clean client rendering
        html_contract = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Pilot Agreement: {company_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f3f4f6; padding: 40px; color: #1f2937; line-height: 1.6; }}
        .contract-box {{ max-width: 850px; margin: 0 auto; background: #ffffff; padding: 48px; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); border-top: 6px solid #10b981; }}
        h1 {{ font-size: 24px; color: #064e3b; margin-top: 0; }}
        .ref-bar {{ font-family: monospace; font-size: 13px; color: #6b7280; background: #f9fafb; padding: 10px 14px; border-radius: 6px; margin-bottom: 24px; border: 1px solid #e5e7eb; }}
        h3 {{ color: #111827; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin-top: 24px; font-size: 16px; }}
        .sig-block {{ display: grid; grid-template-columns: 1fr 1fr; gap: 40px; margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; }}
        .badge {{ background: #ecfdf5; color: #065f46; padding: 4px 10px; border-radius: 9999px; font-weight: bold; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="contract-box">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <h1>TRADENEXUS AI • ENTERPRISE PILOT SERVICE AGREEMENT</h1>
            <span class="badge">30-DAY PAID PILOT</span>
        </div>
        <div class="ref-bar">
            CONTRACT ID: <strong>{contract_id}</strong> | EFFECTIVE: {effective_date} | EXPIRY: {expiry_date}
        </div>
        <p><strong>Customer</strong>: {company_name} (IEC: <code>{iec_code}</code>, GSTIN: <code>{gstin}</code>)<br>
        <strong>Signatory</strong>: {authorized_signatory}, {signatory_title}<br>
        <strong>Pilot Fee</strong>: ₹{monthly_fee_inr:,.2f} + 18% GST (Includes {consignments_quota} Consignment Audits)</p>

        <h3>1. Scope of Services</h3>
        <p>TradeNexus AI provides autonomous, tamper-evident customs clearance dockets, HS-code reconciliations, and EU CBAM XML generation conforming to Regulation (EU) 2023/956.</p>

        <h3>2. Demurrage Indemnity Guarantee</h3>
        <p>TradeNexus AI provides a <strong>₹{cls.DEFAULT_DEMURRAGE_INDEMNITY_CAP_INR:,.2f} direct indemnity shield</strong> against documentation-induced port holds for all dockets marked 'APPROVED'.</p>

        <div class="sig-block">
            <div>
                <strong>TradeNexus AI Technologies</strong><br>
                <em>Aditya Mehra, Founder</em><br><br>
                <code>[DIGITALLY SIGNED VIA OMEGA CORE]</code><br>
                Date: {effective_date}
            </div>
            <div>
                <strong>{company_name}</strong><br>
                <em>{authorized_signatory}, {signatory_title}</em><br><br>
                Signature: ___________________________<br>
                Date: ________________________________
            </div>
        </div>
    </div>
</body>
</html>
"""

        return {
            "contract_id": contract_id,
            "company_name": company_name,
            "effective_date": effective_date,
            "expiry_date": expiry_date,
            "monthly_fee_inr": monthly_fee_inr,
            "consignments_quota": consignments_quota,
            "markdown_agreement": md_contract,
            "html_agreement": html_contract
        }

    @classmethod
    def save_agreements(cls, output_dir: str, contract_dict: Dict[str, Any]) -> Dict[str, str]:
        os.makedirs(output_dir, exist_ok=True)
        safe_name = contract_dict["company_name"].replace(" ", "_").upper()
        
        md_path = os.path.join(output_dir, f"PILOT_AGREEMENT_{safe_name}.md")
        html_path = os.path.join(output_dir, f"PILOT_AGREEMENT_{safe_name}.html")

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(contract_dict["markdown_agreement"])

        with open(html_path, "w", encoding="utf-8") as f:
            f.write(contract_dict["html_agreement"])

        return {"markdown_path": md_path, "html_path": html_path}
